server.port=8001
server.servlet.context-path=/member

spring.datasource.url=jdbc:mariadb://8.137.58.214:3306/train_member?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=train_member
spring.datasource.password=train_member
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#mybatis xml??
mybatis.mapper-locations=classpath:mapper/**/*.xml
logging.level.com.jiawa.train.member.mapper = trace
server.error.include-message=always