GET http://localhost:8000/member/member/count
Accept: application/json

<> 2026-05-13T201007.200.json

###
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile = 12346789

###
POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
    "mobile": "18680701847",
    "code": "8888"
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile = 18680701849&code = 8888

###